version: '3'

services:
  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    restart: always
    volumes:
      - ./mysql/mysqldatabase:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'test'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'pass'
